blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/The-Artificer-of-Ciphers-LLC/sentinel-of-mnemosyne/discussions
    about: Ask questions and discuss ideas here
